// Representative FTSE All-World pool (~105 stocks) covering US, Europe, and Asia-Pacific.
// All tickers are verified to work with Yahoo Finance.
// 10 are drawn daily via date-seeded shuffle in submit-batch.js.

const POOL = [
  // ── United States — Technology ───────────────────────────────────────────
  { sym: 'NVDA',    label: 'Nvidia'             },
  { sym: 'AAPL',    label: 'Apple'              },
  { sym: 'MSFT',    label: 'Microsoft'          },
  { sym: 'AMZN',    label: 'Amazon'             },
  { sym: 'GOOGL',   label: 'Alphabet'           },
  { sym: 'AVGO',    label: 'Broadcom'           },
  { sym: 'META',    label: 'Meta'               },
  { sym: 'TSLA',    label: 'Tesla'              },
  { sym: 'AMD',     label: 'AMD'                },
  { sym: 'INTC',    label: 'Intel'              },
  { sym: 'ORCL',    label: 'Oracle'             },
  { sym: 'CRM',     label: 'Salesforce'         },
  { sym: 'CSCO',    label: 'Cisco'              },
  { sym: 'QCOM',    label: 'Qualcomm'           },
  { sym: 'TXN',     label: 'Texas Instruments'  },
  { sym: 'AMAT',    label: 'Applied Materials'  },
  // ── United States — Financials ────────────────────────────────────────────
  { sym: 'JPM',     label: 'JPMorgan'           },
  { sym: 'BAC',     label: 'Bank of America'    },
  { sym: 'GS',      label: 'Goldman Sachs'      },
  { sym: 'WFC',     label: 'Wells Fargo'        },
  { sym: 'MS',      label: 'Morgan Stanley'     },
  { sym: 'V',       label: 'Visa'               },
  { sym: 'MA',      label: 'Mastercard'         },
  { sym: 'BRK-B',   label: 'Berkshire Hathaway' },
  // ── United States — Healthcare ────────────────────────────────────────────
  { sym: 'LLY',     label: 'Eli Lilly'          },
  { sym: 'JNJ',     label: 'Johnson & Johnson'  },
  { sym: 'PFE',     label: 'Pfizer'             },
  { sym: 'ABBV',    label: 'AbbVie'             },
  { sym: 'MRK',     label: 'Merck'              },
  { sym: 'UNH',     label: 'UnitedHealth'       },
  { sym: 'AMGN',    label: 'Amgen'              },
  // ── United States — Consumer & Industrials ────────────────────────────────
  { sym: 'WMT',     label: 'Walmart'            },
  { sym: 'COST',    label: 'Costco'             },
  { sym: 'HD',      label: 'Home Depot'         },
  { sym: 'PG',      label: 'P&G'                },
  { sym: 'KO',      label: 'Coca-Cola'          },
  { sym: 'PEP',     label: 'PepsiCo'            },
  { sym: 'MCD',     label: "McDonald's"         },
  { sym: 'NKE',     label: 'Nike'               },
  { sym: 'NFLX',    label: 'Netflix'            },
  { sym: 'DIS',     label: 'Disney'             },
  { sym: 'XOM',     label: 'ExxonMobil'         },
  { sym: 'CVX',     label: 'Chevron'            },
  { sym: 'CAT',     label: 'Caterpillar'        },
  { sym: 'RTX',     label: 'RTX Corp'           },
  // ── Europe — Germany ─────────────────────────────────────────────────────
  { sym: 'SAP.DE',  label: 'SAP'                },
  { sym: 'SIE.DE',  label: 'Siemens'            },
  { sym: 'BMW.DE',  label: 'BMW'                },
  { sym: 'MBG.DE',  label: 'Mercedes-Benz'      },
  { sym: 'BAS.DE',  label: 'BASF'               },
  { sym: 'ADS.DE',  label: 'Adidas'             },
  { sym: 'MUV2.DE', label: 'Munich Re'          },
  { sym: 'DBK.DE',  label: 'Deutsche Bank'      },
  { sym: 'HEN3.DE', label: 'Henkel'             },
  // ── Europe — France ───────────────────────────────────────────────────────
  { sym: 'MC.PA',   label: 'LVMH'               },
  { sym: 'OR.PA',   label: "L'Oréal"            },
  { sym: 'SAN.PA',  label: 'Sanofi'             },
  { sym: 'TTE.PA',  label: 'TotalEnergies'      },
  { sym: 'BNP.PA',  label: 'BNP Paribas'        },
  { sym: 'AI.PA',   label: 'Air Liquide'        },
  { sym: 'RMS.PA',  label: 'Hermès'             },
  { sym: 'SU.PA',   label: 'Schneider Electric' },
  // ── Europe — Switzerland ──────────────────────────────────────────────────
  { sym: 'NESN.SW', label: 'Nestlé'             },
  { sym: 'ROG.SW',  label: 'Roche'              },
  { sym: 'NOVN.SW', label: 'Novartis'           },
  { sym: 'ABBN.SW', label: 'ABB'                },
  { sym: 'ZURN.SW', label: 'Zurich Insurance'   },
  // ── Europe — United Kingdom ───────────────────────────────────────────────
  { sym: 'AZN.L',   label: 'AstraZeneca'        },
  { sym: 'SHEL.L',  label: 'Shell'              },
  { sym: 'HSBA.L',  label: 'HSBC'               },
  { sym: 'BP.L',    label: 'BP'                 },
  { sym: 'GSK.L',   label: 'GSK'                },
  { sym: 'ULVR.L',  label: 'Unilever'           },
  { sym: 'RIO.L',   label: 'Rio Tinto'          },
  { sym: 'BHP.L',   label: 'BHP Group'          },
  { sym: 'BARC.L',  label: 'Barclays'           },
  // ── Europe — Netherlands / Nordics ───────────────────────────────────────
  { sym: 'ASML.AS', label: 'ASML'               },
  { sym: 'HEIA.AS', label: 'Heineken'           },
  { sym: 'INGA.AS', label: 'ING Group'          },
  { sym: 'NOK',     label: 'Nokia'              },
  { sym: 'ERIC',    label: 'Ericsson'           },
  // ── Asia-Pacific — Japan (US ADRs) ───────────────────────────────────────
  { sym: 'TM',      label: 'Toyota'             },
  { sym: 'SONY',    label: 'Sony'               },
  { sym: 'HMC',     label: 'Honda'              },
  { sym: 'SFTBY',   label: 'SoftBank'           },
  { sym: 'MUFG',    label: 'Mitsubishi UFJ'     },
  { sym: 'KB',      label: 'KB Financial'       },
  // ── Asia-Pacific — Taiwan / China / India ─────────────────────────────────
  { sym: 'TSM',     label: 'TSMC'               },
  { sym: 'BABA',    label: 'Alibaba'            },
  { sym: 'BIDU',    label: 'Baidu'              },
  { sym: 'TCEHY',   label: 'Tencent'            },
  { sym: 'JD',      label: 'JD.com'             },
  { sym: 'INFY',    label: 'Infosys'            },
  { sym: 'HDB',     label: 'HDFC Bank'          },
  { sym: 'IBN',     label: 'ICICI Bank'         },
  { sym: 'WIT',     label: 'Wipro'              },
  // ── Asia-Pacific — Australia / Other ─────────────────────────────────────
  { sym: 'BHP',     label: 'BHP Group'          },
  { sym: 'RIO',     label: 'Rio Tinto'          },
  { sym: 'NVO',     label: 'Novo Nordisk'       },
  { sym: 'SMFG',    label: 'Sumitomo Mitsui'    },
];

export async function fetchFtsePool() {
  return POOL;
}
