// Representative MSCI World Small Cap pool (~400 stocks) covering developed markets
// across North America, Europe, and Asia-Pacific.
// 10 are drawn daily via date-seeded shuffle in submit-batch.js.
// Tickers that fail Yahoo Finance price lookup are silently filtered by submit-batch.

const POOL = [
  // ── United States — Technology / Semiconductors ───────────────────────────
  { sym: 'QLYS',  label: 'Qualys'                },
  { sym: 'SPSC',  label: 'SPS Commerce'          },
  { sym: 'PRGS',  label: 'Progress Software'     },
  { sym: 'PLUS',  label: 'ePlus'                 },
  { sym: 'MGNI',  label: 'Magnite'               },
  { sym: 'ACLS',  label: 'Axcelis Technologies'  },
  { sym: 'ICHR',  label: 'Ichor Holdings'        },
  { sym: 'DIOD',  label: 'Diodes Inc'            },
  { sym: 'AEIS',  label: 'Advanced Energy'       },
  { sym: 'CLFD',  label: 'Clearfield'            },
  { sym: 'FORM',  label: 'FormFactor'            },
  { sym: 'INTA',  label: 'Intapp'                },
  { sym: 'KLIC',  label: 'Kulicke & Soffa'       },
  { sym: 'SLAB',  label: 'Silicon Labs'          },
  { sym: 'POWI',  label: 'Power Integrations'    },
  { sym: 'VIAV',  label: 'Viavi Solutions'       },
  { sym: 'CALX',  label: 'Calix'                 },
  { sym: 'DGII',  label: 'Digi International'    },
  { sym: 'JAMF',  label: 'Jamf Holding'          },
  { sym: 'CEVA',  label: 'CEVA Inc'              },
  { sym: 'SMTC',  label: 'Semtech'               },
  { sym: 'COHU',  label: 'Cohu Inc'              },
  { sym: 'SSYS',  label: 'Stratasys'             },
  { sym: 'CRUS',  label: 'Cirrus Logic'          },
  { sym: 'LSCC',  label: 'Lattice Semiconductor' },
  { sym: 'RMBS',  label: 'Rambus'                },
  { sym: 'PEGA',  label: 'Pegasystems'           },
  { sym: 'SITM',  label: 'SiTime'                },
  { sym: 'NTGR',  label: 'Netgear'               },
  { sym: 'EVBG',  label: 'Everbridge'            },
  { sym: 'ALRM',  label: 'Alarm.com'             },
  { sym: 'BAND',  label: 'Bandwidth Inc'         },
  { sym: 'DOCN',  label: 'DigitalOcean'          },
  { sym: 'EGHT',  label: '8x8 Inc'               },
  { sym: 'NCNO',  label: 'nCino'                 },
  { sym: 'QTWO',  label: 'Q2 Holdings'           },
  { sym: 'RPAY',  label: 'Repay Holdings'        },
  { sym: 'SCSC',  label: 'ScanSource'            },
  { sym: 'SEMR',  label: 'Semrush'               },
  { sym: 'TASK',  label: 'TaskUs'                },
  { sym: 'YEXT',  label: 'Yext'                  },
  { sym: 'WEAV',  label: 'Weave Communications'  },
  { sym: 'MODN',  label: 'Model N'               },
  { sym: 'SPNS',  label: 'Sapiens International' },
  { sym: 'VRRM',  label: 'Verra Mobility'        },
  { sym: 'FSLY',  label: 'Fastly'                },
  // ── United States — Healthcare ────────────────────────────────────────────
  { sym: 'IRTC',  label: 'iRhythm Technologies'  },
  { sym: 'TMDX',  label: 'TransMedics Group'     },
  { sym: 'LMAT',  label: 'LeMaitre Vascular'     },
  { sym: 'NEOG',  label: 'Neogen Corporation'    },
  { sym: 'NVST',  label: 'Envista Holdings'      },
  { sym: 'PRCT',  label: 'Procept BioRobotics'   },
  { sym: 'INSP',  label: 'Inspire Medical'       },
  { sym: 'SWAV',  label: 'ShockWave Medical'     },
  { sym: 'OMCL',  label: 'Omnicell'              },
  { sym: 'VCEL',  label: 'Vericel Corp'          },
  { sym: 'GKOS',  label: 'Glaukos Corp'          },
  { sym: 'MMSI',  label: 'Merit Medical Systems' },
  { sym: 'OFIX',  label: 'Orthofix Medical'      },
  { sym: 'NARI',  label: 'Inari Medical'         },
  { sym: 'AXNX',  label: 'Axonics'               },
  { sym: 'ACAD',  label: 'ACADIA Pharma'         },
  { sym: 'TNDM',  label: 'Tandem Diabetes'       },
  { sym: 'HALO',  label: 'Halozyme Therapeutics' },
  { sym: 'MGNX',  label: 'MacroGenics'           },
  { sym: 'NVCR',  label: 'NovoCure'              },
  { sym: 'ACCD',  label: 'Accolade Inc'          },
  { sym: 'CNMD',  label: 'Conmed Corp'           },
  { sym: 'HCAT',  label: 'Health Catalyst'       },
  { sym: 'PRVA',  label: 'Privia Health'         },
  { sym: 'SDGR',  label: 'Schrödinger'           },
  { sym: 'TMCI',  label: 'Treace Medical'        },
  { sym: 'XNCR',  label: 'Xencor'               },
  { sym: 'NVAX',  label: 'Novavax'               },
  { sym: 'ANGO',  label: 'AngioDynamics'         },
  { sym: 'SPOK',  label: 'Spok Holdings'         },
  { sym: 'RGEN',  label: 'Repligen Corp'         },
  { sym: 'SGHT',  label: 'Sight Sciences'        },
  // ── United States — Industrials / Defence ────────────────────────────────
  { sym: 'TREX',  label: 'Trex Company'          },
  { sym: 'UFPI',  label: 'UFP Industries'        },
  { sym: 'DORM',  label: 'Dorman Products'       },
  { sym: 'LCII',  label: 'LCI Industries'        },
  { sym: 'CSWI',  label: 'CSW Industrials'       },
  { sym: 'MYRG',  label: 'MYR Group'             },
  { sym: 'PLXS',  label: 'Plexus Corp'           },
  { sym: 'AAON',  label: 'AAON Inc'              },
  { sym: 'KTOS',  label: 'Kratos Defense'        },
  { sym: 'OSIS',  label: 'OSI Systems'           },
  { sym: 'MGRC',  label: 'McGrath RentCorp'      },
  { sym: 'EXPO',  label: 'Exponent Inc'          },
  { sym: 'STRL',  label: 'Sterling Infrastructure'},
  { sym: 'PRIM',  label: 'Primoris Services'     },
  { sym: 'HLIO',  label: 'Helios Technologies'   },
  { sym: 'DXPE',  label: 'DXP Enterprises'       },
  { sym: 'POWL',  label: 'Powell Industries'     },
  { sym: 'ARCB',  label: 'ArcBest'               },
  { sym: 'HUBG',  label: 'Hub Group'             },
  { sym: 'MATX',  label: 'Matson Inc'            },
  { sym: 'ROAD',  label: 'Construction Partners' },
  { sym: 'GFF',   label: 'Griffon Corp'          },
  { sym: 'AZTA',  label: 'Azenta Inc'            },
  { sym: 'HURN',  label: 'Huron Consulting'      },
  { sym: 'WERN',  label: 'Werner Enterprises'    },
  { sym: 'ASTE',  label: 'Astec Industries'      },
  { sym: 'ESAB',  label: 'ESAB Corp'             },
  { sym: 'CNXN',  label: 'PC Connection'         },
  { sym: 'DDD',   label: '3D Systems'            },
  { sym: 'CECO',  label: 'CECO Environmental'    },
  { sym: 'GBX',   label: 'Greenbrier Companies'  },
  { sym: 'GRBK',  label: 'Green Brick Partners'  },
  { sym: 'HZO',   label: 'MarineMax'             },
  { sym: 'KELYA', label: 'Kelly Services'        },
  { sym: 'LMB',   label: 'Limbach Holdings'      },
  { sym: 'MTRN',  label: 'Materion Corp'         },
  { sym: 'MWA',   label: 'Mueller Water Products'},
  { sym: 'NVEE',  label: 'NV5 Global'            },
  { sym: 'PATK',  label: 'Patrick Industries'    },
  { sym: 'PLAB',  label: 'Photronics'            },
  { sym: 'SXI',   label: 'Standex International' },
  { sym: 'TILE',  label: 'Interface Inc'         },
  { sym: 'TRS',   label: 'TriMas Corp'           },
  { sym: 'USLM',  label: 'US Lime & Minerals'    },
  // ── United States — Consumer ──────────────────────────────────────────────
  { sym: 'WING',  label: 'Wingstop'              },
  { sym: 'BOOT',  label: 'Boot Barn Holdings'    },
  { sym: 'HIMS',  label: 'Hims & Hers Health'    },
  { sym: 'CELH',  label: 'Celsius Holdings'      },
  { sym: 'CAVA',  label: 'Cava Group'            },
  { sym: 'IPAR',  label: 'Inter Parfums'         },
  { sym: 'TMHC',  label: 'Taylor Morrison Home'  },
  { sym: 'XPOF',  label: 'Xponential Fitness'    },
  { sym: 'SHAK',  label: 'Shake Shack'           },
  { sym: 'PTLO',  label: 'Portillo\'s'           },
  { sym: 'JACK',  label: 'Jack in the Box'       },
  { sym: 'BJRI',  label: 'BJ\'s Restaurants'     },
  { sym: 'CAKE',  label: 'Cheesecake Factory'    },
  { sym: 'DINE',  label: 'Dine Brands'           },
  { sym: 'FWRG',  label: 'First Watch Restaurant'},
  { sym: 'LOCO',  label: 'El Pollo Loco'         },
  { sym: 'RRGB',  label: 'Red Robin Gourmet'     },
  { sym: 'BOWL',  label: 'Bowlero Corp'          },
  { sym: 'HAYW',  label: 'Hayward Holdings'      },
  { sym: 'IBP',   label: 'Installed Building'    },
  { sym: 'BLD',   label: 'TopBuild Corp'         },
  { sym: 'LESL',  label: 'Leslie\'s Inc'         },
  { sym: 'PLNT',  label: 'Planet Fitness'        },
  { sym: 'DRVN',  label: 'Driven Brands'         },
  { sym: 'LAZY',  label: 'Lazydays Holdings'     },
  { sym: 'CURV',  label: 'Torrid Holdings'       },
  // ── United States — Financials ────────────────────────────────────────────
  { sym: 'ENVA',  label: 'Enova International'   },
  { sym: 'KFRC',  label: 'Kforce'                },
  { sym: 'TFIN',  label: 'Triumph Financial'     },
  { sym: 'FCFS',  label: 'FirstCash Holdings'    },
  { sym: 'WSFS',  label: 'WSFS Financial'        },
  { sym: 'HMST',  label: 'HomeStreet Inc'        },
  { sym: 'BANF',  label: 'BancFirst'             },
  { sym: 'HOMB',  label: 'Home BancShares'       },
  { sym: 'SFNC',  label: 'Simmons First'         },
  { sym: 'IBOC',  label: 'International Bancshares'},
  { sym: 'WAFD',  label: 'WaFd Inc'              },
  { sym: 'CVBF',  label: 'CVB Financial'         },
  { sym: 'FFIN',  label: 'First Financial Bankshares'},
  { sym: 'CVCO',  label: 'Cavco Industries'      },
  { sym: 'JRVR',  label: 'James River Group'     },
  { sym: 'WRLD',  label: 'World Acceptance'      },
  { sym: 'QCRH',  label: 'QCR Holdings'          },
  { sym: 'HTLF',  label: 'Heartland BancCorp'    },
  { sym: 'PFSI',  label: 'PennyMac Financial'    },
  { sym: 'PRG',   label: 'PROG Holdings'         },
  { sym: 'PSMT',  label: 'PriceSmart'            },
  { sym: 'COOP',  label: 'Mr. Cooper Group'      },
  // ── United States — Energy / Materials ───────────────────────────────────
  { sym: 'CIVI',  label: 'Civitas Resources'     },
  { sym: 'MGY',   label: 'Magnolia Oil & Gas'    },
  { sym: 'TALO',  label: 'Talos Energy'          },
  { sym: 'ESTE',  label: 'Earthstone Energy'     },
  { sym: 'SM',    label: 'SM Energy'             },
  { sym: 'REX',   label: 'REX Energy'            },
  { sym: 'VTLE',  label: 'Vital Energy'          },
  // ── Europe — Germany ──────────────────────────────────────────────────────
  { sym: 'AIXA.DE',  label: 'Aixtron SE'         },
  { sym: 'EVT.DE',   label: 'Evotec SE'          },
  { sym: 'NDX1.DE',  label: 'Nordex SE'          },
  { sym: 'SGL.DE',   label: 'SGL Carbon'         },
  { sym: 'DUE.DE',   label: 'Dürr AG'            },
  { sym: 'GXI.DE',   label: 'Gerresheimer AG'    },
  { sym: 'AFX.DE',   label: 'Carl Zeiss Meditec' },
  { sym: 'BOSS.DE',  label: 'Hugo Boss'          },
  { sym: 'HFG.DE',   label: 'HelloFresh'         },
  { sym: 'PNE.DE',   label: 'PNE AG'             },
  { sym: 'VBK.DE',   label: 'Verbio SE'          },
  { sym: 'HAG.DE',   label: 'Hensoldt AG'        },
  { sym: 'TUI1.DE',  label: 'TUI Group'          },
  { sym: 'UTDI.DE',  label: 'United Internet'    },
  { sym: 'KSB.DE',   label: 'KSB SE'            },
  { sym: 'PSM.DE',   label: 'ProSiebenSat.1'    },
  { sym: 'MBB.DE',   label: 'MBB SE'            },
  // ── Europe — United Kingdom ───────────────────────────────────────────────
  { sym: 'ITV.L',    label: 'ITV plc'            },
  { sym: 'RWS.L',    label: 'RWS Holdings'       },
  { sym: 'JDW.L',    label: 'J D Wetherspoon'    },
  { sym: 'BOO.L',    label: 'Boohoo Group'       },
  { sym: 'PETS.L',   label: 'Pets at Home'       },
  { sym: 'IGG.L',    label: 'IG Group'           },
  { sym: 'DFS.L',    label: 'DFS Furniture'      },
  { sym: 'PAGE.L',   label: 'PageGroup'          },
  { sym: 'CARD.L',   label: 'Card Factory'       },
  { sym: 'GNS.L',    label: 'Genus plc'          },
  { sym: 'NCC.L',    label: 'NCC Group'          },
  { sym: 'FOUR.L',   label: '4imprint Group'     },
  { sym: 'MAB.L',    label: 'Mitchells & Butlers'},
  { sym: 'ASCL.L',   label: 'Ascential plc'      },
  { sym: 'AO.L',     label: 'AO World'           },
  { sym: 'MNZS.L',   label: 'Moonpig Group'      },
  { sym: 'MONY.L',   label: 'Moneysupermarket'   },
  { sym: 'HGT.L',    label: 'HgCapital Trust'    },
  // ── Europe — France ───────────────────────────────────────────────────────
  { sym: 'FNAC.PA',  label: 'Fnac Darty'         },
  { sym: 'MRN.PA',   label: 'Mersen SA'          },
  { sym: 'FREY.PA',  label: 'Freyr Battery'      },
  { sym: 'INVE.PA',  label: 'Inversiones Agropec.'},
  { sym: 'MLNP.PA',  label: 'Nanobiotix'         },
  { sym: 'ALDEI.PA', label: 'DEI Holding'        },
  // ── Europe — Netherlands ──────────────────────────────────────────────────
  { sym: 'FLOW.AS',  label: 'Flow Traders'       },
  { sym: 'ALFEN.AS', label: 'Alfen NV'           },
  { sym: 'ACOMO.AS', label: 'Amsterdam Commodities'},
  { sym: 'FAGR.AS',  label: 'ForFarmers'         },
  { sym: 'NSI.AS',   label: 'NSI NV'             },
  // ── Europe — Switzerland ──────────────────────────────────────────────────
  { sym: 'TEMN.SW',  label: 'Temenos AG'         },
  { sym: 'BCHN.SW',  label: 'Baloise Holding'    },
  { sym: 'HIAG.SW',  label: 'HIAG Immobilien'    },
  { sym: 'COTN.SW',  label: 'Cottonfield'        },
  // ── Europe — Sweden ───────────────────────────────────────────────────────
  { sym: 'SINCH.ST',    label: 'Sinch AB'        },
  { sym: 'VITEC-B.ST',  label: 'Vitec Software'  },
  { sym: 'BUFAB.ST',    label: 'Bufab Group'     },
  { sym: 'MYCRONIC.ST', label: 'Mycronic AB'     },
  { sym: 'NCAB.ST',     label: 'NCAB Group'      },
  { sym: 'ACAST.ST',    label: 'Acast AB'        },
  { sym: 'NOTE.ST',     label: 'NOTE AB'         },
  { sym: 'LAGR-B.ST',   label: 'Lagercrantz Group'},
  { sym: 'BURE.ST',     label: 'Bure Equity'     },
  { sym: 'EMBRAC-B.ST', label: 'Embracer Group'  },
  // ── Europe — Denmark ──────────────────────────────────────────────────────
  { sym: 'NETC.CO',   label: 'Netcompany Group'  },
  { sym: 'AMBU-B.CO', label: 'Ambu A/S'          },
  { sym: 'GN.CO',     label: 'GN Store Nord'     },
  { sym: 'CHEMM.CO',  label: 'ChemoMetec'        },
  { sym: 'MATAS.CO',  label: 'Matas A/S'         },
  { sym: 'DFDS.CO',   label: 'DFDS A/S'          },
  // ── Europe — Norway ───────────────────────────────────────────────────────
  { sym: 'AKSO.OL',   label: 'Aker Solutions'    },
  { sym: 'NEL.OL',    label: 'Nel ASA'           },
  { sym: 'KAHOT.OL',  label: 'Kahoot!'           },
  { sym: 'BOUVET.OL', label: 'Bouvet ASA'        },
  { sym: 'DNO.OL',    label: 'DNO ASA'           },
  { sym: 'PGS.OL',    label: 'PGS ASA'           },
  // ── Europe — Finland ──────────────────────────────────────────────────────
  { sym: 'ORNBV.HE',  label: 'Orion Corporation' },
  { sym: 'QTCOM.HE',  label: 'Qt Group'          },
  { sym: 'KEMIRA.HE', label: 'Kemira Oyj'        },
  { sym: 'FSKRS.HE',  label: 'Fiskars Oyj'       },
  { sym: 'TIETO.HE',  label: 'TietoEVRY'         },
  // ── Europe — Spain ────────────────────────────────────────────────────────
  { sym: 'MAP.MC',    label: 'Mapfre SA'         },
  { sym: 'TRE.MC',    label: 'Técnicas Reunidas' },
  { sym: 'MRL.MC',    label: 'Meliá Hotels'      },
  { sym: 'SOL.MC',    label: 'Solaria Energía'   },
  { sym: 'ENCE.MC',   label: 'Ence Energía'      },
  // ── Europe — Italy ────────────────────────────────────────────────────────
  { sym: 'SFER.MI',   label: 'Safilo Group'      },
  { sym: 'MARR.MI',   label: 'MARR SpA'          },
  { sym: 'BC.MI',     label: 'Brunello Cucinelli' },
  // ── Europe — Belgium ──────────────────────────────────────────────────────
  { sym: 'ONTEX.BR',  label: 'Ontex Group'       },
  { sym: 'WDP.BR',    label: 'WDP NV'            },
  // ── Europe — Austria ──────────────────────────────────────────────────────
  { sym: 'VIG.VI',    label: 'Vienna Insurance'  },
  { sym: 'FACC.VI',   label: 'FACC AG'           },
  // ── Asia-Pacific — Japan ──────────────────────────────────────────────────
  { sym: '4686.T',  label: 'Just Systems'        },
  { sym: '6457.T',  label: 'Glory Ltd'           },
  { sym: '6028.T',  label: 'TechnoPro Holdings'  },
  { sym: '6952.T',  label: 'Casio Computer'      },
  { sym: '3765.T',  label: 'GungHo Online'       },
  { sym: '2432.T',  label: 'DeNA Co'             },
  { sym: '6976.T',  label: 'Taiyo Yuden'         },
  { sym: '6770.T',  label: 'Alps Alpine'         },
  { sym: '5332.T',  label: 'Toto Ltd'            },
  { sym: '6473.T',  label: 'JTEKT Corp'          },
  { sym: '2871.T',  label: 'Nichirei Corp'       },
  { sym: '7278.T',  label: 'Exedy Corp'          },
  { sym: '6508.T',  label: 'Meidensha Corp'      },
  { sym: '3697.T',  label: 'SHIFT Inc'           },
  { sym: '2593.T',  label: 'Ito En Ltd'          },
  { sym: '5301.T',  label: 'Tokai Carbon'        },
  { sym: '4272.T',  label: 'Nippon Kayaku'       },
  { sym: '9684.T',  label: 'Square Enix'         },
  { sym: '9697.T',  label: 'Capcom Co'           },
  { sym: '6645.T',  label: 'OMRON Corp'          },
  { sym: '3288.T',  label: 'Open House Group'    },
  { sym: '2413.T',  label: 'M3 Inc'              },
  { sym: '3659.T',  label: 'Nexon Co'            },
  { sym: '4519.T',  label: 'Chugai Pharma'       },
  { sym: '4543.T',  label: 'Terumo Corp'         },
  { sym: '6988.T',  label: 'Nitto Denko'         },
  { sym: '5101.T',  label: 'Yokohama Rubber'     },
  { sym: '3626.T',  label: 'TIS Inc'             },
  { sym: '9381.T',  label: 'AIT Corp'            },
  { sym: '1928.T',  label: 'Sekisui House'       },
  { sym: '7936.T',  label: 'ASICS Corp'          },
  { sym: '3086.T',  label: 'J. Front Retailing'  },
  { sym: '4151.T',  label: 'Kyowa Kirin'         },
  { sym: '3064.T',  label: 'MonotaRO'            },
  { sym: '3405.T',  label: 'Kuraray Co'          },
  { sym: '5201.T',  label: 'AGC Inc'             },
  { sym: '8473.T',  label: 'SBI Holdings'        },
  { sym: '9202.T',  label: 'ANA Holdings'        },
  { sym: '7012.T',  label: 'Kawasaki Heavy Ind.' },
  { sym: '4507.T',  label: 'Shionogi'            },
  // ── Asia-Pacific — Australia ──────────────────────────────────────────────
  { sym: 'APX.AX',  label: 'Appen Ltd'           },
  { sym: 'PPT.AX',  label: 'Perpetual Ltd'       },
  { sym: 'IEL.AX',  label: 'IDP Education'       },
  { sym: 'GNC.AX',  label: 'GrainCorp'           },
  { sym: 'NXT.AX',  label: 'NextDC'              },
  { sym: 'SXL.AX',  label: 'Southern Cross Media'},
  { sym: 'MFG.AX',  label: 'Magellan Financial'  },
  { sym: 'PTM.AX',  label: 'Platinum Asset Mgmt' },
  { sym: 'NAN.AX',  label: 'Nanosonics'          },
  { sym: 'OML.AX',  label: 'oOh!media'           },
  { sym: 'ZIP.AX',  label: 'Zip Co'              },
  { sym: 'EML.AX',  label: 'EML Payments'        },
  { sym: 'HUB.AX',  label: 'Hub24'               },
  { sym: 'SLC.AX',  label: 'Superloop'           },
  { sym: 'ADH.AX',  label: 'Adairs Ltd'          },
  { sym: 'BKW.AX',  label: 'Brickworks'          },
  { sym: 'CIA.AX',  label: 'Champion Iron'       },
  { sym: 'SCP.AX',  label: 'SCA Property Group'  },
  { sym: 'A2M.AX',  label: 'a2 Milk Company'     },
  { sym: 'PPS.AX',  label: 'Praemium'            },
  { sym: 'VHT.AX',  label: 'Volpara Health'      },
  { sym: 'FLT.AX',  label: 'Flight Centre'       },
  { sym: 'WEB.AX',  label: 'Webjet'              },
  { sym: 'ARB.AX',  label: 'ARB Corp'            },
  { sym: 'RWC.AX',  label: 'Reliance Worldwide'  },
  { sym: 'PNV.AX',  label: 'PolyNovo'            },
  { sym: 'BRG.AX',  label: 'Breville Group'      },
  { sym: 'ING.AX',  label: 'Inghams Group'       },
  { sym: 'TLX.AX',  label: 'Telix Pharma'        },
  // ── Asia-Pacific — Canada ─────────────────────────────────────────────────
  { sym: 'KXS.TO',  label: 'Kinaxis'             },
  { sym: 'ENGH.TO', label: 'Enghouse Systems'    },
  { sym: 'LSPD.TO', label: 'Lightspeed Commerce' },
  { sym: 'DCBO.TO', label: 'Docebo'              },
  { sym: 'WELL.TO', label: 'WELL Health Tech'    },
  { sym: 'GDI.TO',  label: 'GDI Integrated Fac.' },
  { sym: 'BDT.TO',  label: 'Bird Construction'   },
  { sym: 'SIS.TO',  label: 'Savaria Corp'        },
  { sym: 'PXT.TO',  label: 'Parex Resources'     },
  { sym: 'TOY.TO',  label: 'Spin Master Corp'    },
  { sym: 'ERO.TO',  label: 'Ero Copper'          },
  { sym: 'KITS.TO', label: 'Kits Eyecare'        },
  { sym: 'REAL.TO', label: 'Real Brokerage'      },
  { sym: 'MDF.TO',  label: 'mdf commerce'        },
  { sym: 'ATZ.TO',  label: 'Aritzia'             },
  { sym: 'MFI.TO',  label: 'Maple Leaf Foods'    },
  { sym: 'NFI.TO',  label: 'NFI Group'           },
  { sym: 'PBH.TO',  label: 'Premium Brands'      },
  { sym: 'SJ.TO',   label: 'Stella-Jones'        },
  { sym: 'TSU.TO',  label: 'Trisura Group'       },
  { sym: 'MAL.TO',  label: 'Magellan Aerospace'  },
  // ── Asia-Pacific — New Zealand ────────────────────────────────────────────
  { sym: 'A2M.NZ',  label: 'a2 Milk (NZX)'      },
  { sym: 'SKC.NZ',  label: 'SkyCity Entertainment'},
  { sym: 'NZX.NZ',  label: 'NZX Ltd'            },
  // ── Asia-Pacific — Singapore ──────────────────────────────────────────────
  { sym: 'S58.SI',   label: 'SATS Ltd'           },
  { sym: 'C07.SI',   label: 'Jardine C&C'        },
  { sym: 'C2PU.SI',  label: 'Parkway Life REIT'  },
];

export async function fetchMsciSmallCapPool() {
  return POOL;
}
